### ISSUE TITLE
-r flag with option "eark" causing ClassNotFoundException in version 2.3.0

### ISSUE THREAD

**Issue by mmjohansson** [keeps/commons-ip#132]
Hello,

Running the following command (using Java 8):
`java -jar commons-ip2-cli-2.3.0.jar validate -i uuid-8108ae37-d8e0-46c4-bb8b-f72c8a6d4a43.zip -o ./reports -r eark`

Gives the following exception:
`Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/util/JacksonFeature
        at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:656)
        at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:558)
        at org.roda_project.commons_ip2.validator.reporter.ValidationReportOutputJSONPyIP.writeReport(ValidationReportOutputJSONPyIP.java:81)
        at org.roda_project.commons_ip2.validator.EARKPyIPValidator.validate(EARKPyIPValidator.java:206)
        at org.roda_project.commons_ip2.validator.CLI.CLIValidator.validate(CLIValidator.java:224)
        at org.roda_project.commons_ip2.validator.CLI.CLIValidator.start(CLIValidator.java:157)
        at org.roda_project.commons_ip2.validator.CLI.Main.main(Main.java:30)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.util.JacksonFeature
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)`

It was working fine with the previous version (2.2.1).
